name: "opensyd_flutter"
author: Sergio Lisan <sels@venosyd.com>
publish_to: "none"

version: 3.0.0+25

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  clipboard: 
  flutter:
    sdk: flutter
  flutter_cursor:
  flutter_statusbarcolor: 
  flutter_webview_plugin:
  font_awesome_flutter: 
  opensyd_dart:
    git: git@github.com:venosyd/opensyd_dart.git
  pdf: 
  shared_preferences: 
  